### ISSUE TITLE
Why not to write your own license without a lawyer involved

### ISSUE THREAD

**Issue by asiekierka** [TheRandomLabs/TheRandomLicense#1]
Your license's "2." is an ex post facto which is legally unenforceable in most jurisdictions. Also, "changing it is allowed" is particularly vague - can I simply change it and agree to the changed document instead?

Crediting "visibly" is also vague - is size 8 Arial on the footer of a website in paragraph six visible? Probably.

Just use MIT if you want attribution (in the form of the copyright notice being kept as-is, which is something most MIT-using devs don't realize - you have to keep all of them!).

**Comment by TheRandomLabs** [comment]
Okay, thanks. I mainly just wanted a license that allowed others to change the license as well.

**Comment by falkreon** [comment]
I'm not a lawyer, so this isn't strictly legal advice, but:

  * The modification clause in the preamble is really, really unclear. Could I write "poop" on a napkin and claim that it's TheRandomLicense? Could I show my napkin and claim that it's what I agreed to when I used something released under TRL?

  * Item 1 is insufficiently worded. Usually you'll find specific uses enumerated with wording like "including without limitation" or "including but not limited to". What these enumerations do is help protect the end-user when they're engaged in those activities. If they copy the software, they have a license that says specifically that they can copy the software provided that the other points hold. It simplifies legal proceedings and clarifies the interpretation.

  * The aim of item 2 is to set up an ex post facto, where you alter a law or agreement after it's been agreed to.  It's illegal, but even if we were somehow able to legally agree to it, it undercuts the protections to the user from item 1 by claiming you can remove them at any time.

  * Any one of these pieces is potentially grounds to strike out the whole agreement, because there is no severability clause. In that case, this whole thing reverts to "all rights reserved", which is the opposite of what you wanted.

The goal here is to protect people and give them confidence that they can use, share, modify, and share modifications. Keep in mind that none of these licenses have to be exclusive; if you want to grant someone more rights than, say, MIT, you can have a simple email exchange and establish a license agreement with them, granting them CC0 permissions or whatever you feel is appropriate. But a handwritten license like this is dangerous - not to you, but to the user.

**Comment by TheRandomLabs** [comment]
Yeah, I know, that's why I'm changing the licenses on all of my projects to avoid confusion.
